name: "release templates"

on:
  workflow_dispatch:

jobs:
  release-temaplates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Publish Templates
        id: templates
        uses: devcontainers/action@v1
        with:
          templates-namespace: ${{github.actor}}/devcontainer-templates
          publish-templates: true
          base-path-to-templates: ./src
          generate-docs: true,
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
